### ISSUE TITLE
problem generator

### ISSUE THREAD

**Issue by kwangswei** [Heo-H/kakao-blind-2019-2nd-server-simulator#4]
와 소름!!!
일부만 빼고 놀랍도록 제 코드와 유사하네요.

엘리베이터 트래픽은 다음과 같이 모델링할 수 있어요
- outgoing traffic (from somewhere to 1)
- incoming traffic (from 1 to somewhere)
- interfloor traffic (between floors)

데이터 모델은 저 3가지 타입의 조합 비율로 조절할 수 있습니다.
p1 은 단순 저 조합의 비율을 조율해서 만들었고,
p2 는 제약 조건에 따라 층을 나눠준 것이지요. 
허허님이 하신 것처럼요. 

대박입니다 💯 

굳이 지적하자면, timestamp 증가값 정도..? 저는 그냥 정규분포에 mean, variance 를 조절해가며 적당히 간격을 조절했어요. 엘리베이터 유저의 간격은 굉장히 중요한 포인트가 되기도 합니다. 엘리베이터가 idle 상태일 때 어느 지점으로 이동시키는지도 전체 성능에 영향을 줄 수 있거든요. 이를테면 incoming traffic 이 많은 모델이라면 idle 상태일 때 당연히 1층으로 미리 보내야겠죠.

따라서 timestamp 간 간격이 너무 짧기만 하면 요런 알고리즘의 영향이 희석되어버립니다.

이런 부분들 고민해보면 더 좋은 데이터 제너레이터가 될 거 같아요

**Comment by Heo-H** [comment]
우와... 가독성이 좋지 못한 코드임에도 불구하고 읽어주셔서 감사합니다!


알고리즘의 효율성을 판단하는 프로그램인 만큼 데이터 모델 구성에 비중을 많이 두었어야 했군요. 빨리 서버를 돌려보고 싶은 마음에 중요한걸 놓치고 말았네요...
말씀해주신 내용을 토대로 더 고민해서 지금보다 더 의미 있는 모델로 발전시켜보겠습니다.^^


저도 시험에 대한 느낀점을 말씀드릴게요.
이번 오프라인 시험을 보면서 느낀점이 많았습니다.
처음에는 2차 코딩 테스트에 굉장히 자신이 있었어요. 예전에 개인 프로젝트를 하면서 유지 보수에 관심을 가졌고, 코딩 스타일이나 디자인 패턴 등 코드 품질 관련 이슈들을 접하면서 설계 능력을 키웠어요. 알고리즘보다 프로젝트 설계에 더 자신이 있었으니, 2차 시험은 여유롭게 해결할 수 있을 것이라 생각했죠.

하지만 문제를 본 순간 정말 오랜만에 어디서부터 손대야 할지 막막한 느낌을 받았습니다. 쉬운 문제들만 해결하다 보니 제 설계 능력을 과대평가했던 거죠.

파이썬으로 참가할 생각으로 갔다가 언어를 자바로 변경하는 바람에 서버 통신에만 1시간이나 쏟았어요. 새로운 것을 습득하는 능력의 중요성도 직접 느꼈습니다.ㅋㅋㅋ

결국 시간에 쫓기면서 알고리즘은 뒷전이고, 일단 작동하는 구조부터 만들자라는 목표로 바쁘게 코딩했습니다. 다행이 작동은 했지만 점점 코드는 엉키고, 특히 최적화 알고리즘을 도입할땐 오히려 엘리베이터가 망가져버렸어요.ㅋㅋ

이런 과정들을 거치면서 설계 능력을 더 키워야겠다는 생각이 많이 들었습니다.

아 그리고 테스트 케이스들이 정말 실제 상황같이 구성돼있어서 더 재미있었습니다. 정말 제가 문제를 해결하고 있다는 느낌을 받았어요.

재미있는 문제 만들어주셔서 감사합니다~!

**Comment by Heo-H** [comment]
#6 
피드백 주신 내용대로 개선해보았습니다.
이전에 급하게 만드느라 구조적으로도 아쉬웠던 부분이 많아서 다시 설계했는데, 분명 제가 생각 못한 허점이나 더 좋은 구조가 있을 것 같습니다.^^;
바쁘시겠지만 혹시 나중에라도 시간이 되실때 한번만 더 리뷰를 부탁드려도 될까요?
